/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTypeItemRequestBuilder, WithTypeItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleInspections/ByType/{bookingId}
 */
export interface WithBookingItemRequestBuilder extends BaseRequestBuilder<WithBookingItemRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehicleInspections.ByType.item.item collection
     * @param type Unique identifier of the item
     * @returns {WithTypeItemRequestBuilder}
     */
     byType(type: number) : WithTypeItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithBookingItemRequestBuilderUriTemplate = "{+baseurl}/api/VehicleInspections/ByType/{bookingId}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithBookingItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithBookingItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byType: {
        requestsMetadata: WithTypeItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["type"],
    },
};
/* tslint:enable */
/* eslint-enable */
