/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVehicleIncidentPhotoDtoFromDiscriminatorValue, type VehicleIncidentPhotoDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleIncidentPhotos/ByIncident/{incidentId}
 */
export interface WithIncidentItemRequestBuilder extends BaseRequestBuilder<WithIncidentItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VehicleIncidentPhotoDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VehicleIncidentPhotoDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithIncidentItemRequestBuilderUriTemplate = "{+baseurl}/api/VehicleIncidentPhotos/ByIncident/{incidentId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithIncidentItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithIncidentItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createVehicleIncidentPhotoDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
