/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBookingDtoFromDiscriminatorValue, serializeBookingDto, serializeBookingInputDto, type BookingDto, type BookingInputDto } from '../../models/index.js';
// @ts-ignore
import { ByCustomerRequestBuilderNavigationMetadata, type ByCustomerRequestBuilder } from './byCustomer/index.js';
// @ts-ignore
import { ByVehicleRequestBuilderNavigationMetadata, type ByVehicleRequestBuilder } from './byVehicle/index.js';
// @ts-ignore
import { BookingsItemRequestBuilderRequestsMetadata, type BookingsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Bookings
 */
export interface BookingsRequestBuilder extends BaseRequestBuilder<BookingsRequestBuilder> {
    /**
     * The ByCustomer property
     */
    get byCustomer(): ByCustomerRequestBuilder;
    /**
     * The ByVehicle property
     */
    get byVehicle(): ByVehicleRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.Bookings.item collection
     * @param id Unique identifier of the item
     * @returns {BookingsItemRequestBuilder}
     */
     byId(id: number) : BookingsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BookingDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BookingDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BookingDto>}
     */
     post(body: BookingInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BookingDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: BookingInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BookingsRequestBuilderUriTemplate = "{+baseurl}/api/Bookings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BookingsRequestBuilderNavigationMetadata: Record<Exclude<keyof BookingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: BookingsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    byCustomer: {
        navigationMetadata: ByCustomerRequestBuilderNavigationMetadata,
    },
    byVehicle: {
        navigationMetadata: ByVehicleRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BookingsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BookingsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBookingDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: BookingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createBookingDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeBookingInputDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
