/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithIncidentItemRequestBuilder, WithIncidentItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleIncidentPhotos/ByIncident
 */
export interface ByIncidentRequestBuilder extends BaseRequestBuilder<ByIncidentRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehicleIncidentPhotos.ByIncident.item collection
     * @param incidentId Unique identifier of the item
     * @returns {WithIncidentItemRequestBuilder}
     */
     byIncidentId(incidentId: number) : WithIncidentItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByIncidentRequestBuilderUriTemplate = "{+baseurl}/api/VehicleIncidentPhotos/ByIncident";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByIncidentRequestBuilderNavigationMetadata: Record<Exclude<keyof ByIncidentRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byIncidentId: {
        requestsMetadata: WithIncidentItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["incidentId"],
    },
};
/* tslint:enable */
/* eslint-enable */
