/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBookingItemRequestBuilder, WithBookingItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleInspections/ByType
 */
export interface ByTypeRequestBuilder extends BaseRequestBuilder<ByTypeRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehicleInspections.ByType.item collection
     * @param bookingId Unique identifier of the item
     * @returns {WithBookingItemRequestBuilder}
     */
     byBookingId(bookingId: number) : WithBookingItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByTypeRequestBuilderUriTemplate = "{+baseurl}/api/VehicleInspections/ByType";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByTypeRequestBuilderNavigationMetadata: Record<Exclude<keyof ByTypeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBookingId: {
        navigationMetadata: WithBookingItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["bookingId"],
    },
};
/* tslint:enable */
/* eslint-enable */
