services:
  backend:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile.dev}
    ports:
      - "5000:80"
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      mysql:
        condition: service_healthy
