/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createQuotationDtoFromDiscriminatorValue, serializeQuotationDto, serializeQuotationInputDto, type QuotationDto, type QuotationInputDto } from '../../models/index.js';
// @ts-ignore
import { QuotationsItemRequestBuilderRequestsMetadata, type QuotationsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Quotations
 */
export interface QuotationsRequestBuilder extends BaseRequestBuilder<QuotationsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.Quotations.item collection
     * @param id Unique identifier of the item
     * @returns {QuotationsItemRequestBuilder}
     */
     byId(id: number) : QuotationsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QuotationDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QuotationDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<QuotationDto>}
     */
     post(body: QuotationInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<QuotationDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: QuotationInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const QuotationsRequestBuilderUriTemplate = "{+baseurl}/api/Quotations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const QuotationsRequestBuilderNavigationMetadata: Record<Exclude<keyof QuotationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: QuotationsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const QuotationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: QuotationsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createQuotationDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: QuotationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createQuotationDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeQuotationInputDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
