/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithVehicleItemRequestBuilder, WithVehicleItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehiclePricings/ByVehicleAndSeason
 */
export interface ByVehicleAndSeasonRequestBuilder extends BaseRequestBuilder<ByVehicleAndSeasonRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehiclePricings.ByVehicleAndSeason.item collection
     * @param vehicleId Unique identifier of the item
     * @returns {WithVehicleItemRequestBuilder}
     */
     byVehicleId(vehicleId: number) : WithVehicleItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByVehicleAndSeasonRequestBuilderUriTemplate = "{+baseurl}/api/VehiclePricings/ByVehicleAndSeason";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByVehicleAndSeasonRequestBuilderNavigationMetadata: Record<Exclude<keyof ByVehicleAndSeasonRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byVehicleId: {
        navigationMetadata: WithVehicleItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["vehicleId"],
    },
};
/* tslint:enable */
/* eslint-enable */
