/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSeasonDtoFromDiscriminatorValue, type SeasonDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Seasons/ByYear/{year}
 */
export interface WithYearItemRequestBuilder extends BaseRequestBuilder<WithYearItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SeasonDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SeasonDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithYearItemRequestBuilderUriTemplate = "{+baseurl}/api/Seasons/ByYear/{year}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithYearItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithYearItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSeasonDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
