/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVehicleIncidentDtoFromDiscriminatorValue, type VehicleIncidentDto } from '../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleIncidents/ByInspection/{inspectionId}
 */
export interface WithInspectionItemRequestBuilder extends BaseRequestBuilder<WithInspectionItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VehicleIncidentDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VehicleIncidentDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithInspectionItemRequestBuilderUriTemplate = "{+baseurl}/api/VehicleIncidents/ByInspection/{inspectionId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithInspectionItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithInspectionItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createVehicleIncidentDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
