/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehiclePricings/Calculate
 */
export interface CalculateRequestBuilder extends BaseRequestBuilder<CalculateRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<number>}
     */
     get(requestConfiguration?: RequestConfiguration<CalculateRequestBuilderGetQueryParameters> | undefined) : Promise<number | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<CalculateRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface CalculateRequestBuilderGetQueryParameters {
    endDate?: Date;
    startDate?: Date;
    vehicleId?: number;
}
/**
 * Uri template for the request builder.
 */
export const CalculateRequestBuilderUriTemplate = "{+baseurl}/api/VehiclePricings/Calculate{?endDate*,startDate*,vehicleId*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const CalculateRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CalculateRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "number",
    },
};
/* tslint:enable */
/* eslint-enable */
