services:
  backend:
    build:
      context: ../backend
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "5000:80"
    volumes:
      - ../backend:/src
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  # sdk:
  #   image: mcr.microsoft.com/dotnet/sdk:8.0
  #   volumes:
  #     - ../backend:/src
  #   working_dir: /src
  #   networks:
  #     - crm-network

networks:
  crm-network:
    driver: bridge
