/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithVehicleItemRequestBuilder, WithVehicleItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Bookings/ByVehicle
 */
export interface ByVehicleRequestBuilder extends BaseRequestBuilder<ByVehicleRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.Bookings.ByVehicle.item collection
     * @param vehicleId Unique identifier of the item
     * @returns {WithVehicleItemRequestBuilder}
     */
     byVehicleId(vehicleId: number) : WithVehicleItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByVehicleRequestBuilderUriTemplate = "{+baseurl}/api/Bookings/ByVehicle";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByVehicleRequestBuilderNavigationMetadata: Record<Exclude<keyof ByVehicleRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byVehicleId: {
        requestsMetadata: WithVehicleItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["vehicleId"],
    },
};
/* tslint:enable */
/* eslint-enable */
