/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMaintenanceRecordDtoFromDiscriminatorValue, serializeMaintenanceRecordDto, serializeMaintenanceRecordInputDto, type MaintenanceRecordDto, type MaintenanceRecordInputDto } from '../../models/index.js';
// @ts-ignore
import { MaintenanceRecordsItemRequestBuilderRequestsMetadata, type MaintenanceRecordsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/MaintenanceRecords
 */
export interface MaintenanceRecordsRequestBuilder extends BaseRequestBuilder<MaintenanceRecordsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.MaintenanceRecords.item collection
     * @param id Unique identifier of the item
     * @returns {MaintenanceRecordsItemRequestBuilder}
     */
     byId(id: number) : MaintenanceRecordsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaintenanceRecordDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaintenanceRecordDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MaintenanceRecordDto>}
     */
     post(body: MaintenanceRecordInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MaintenanceRecordDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MaintenanceRecordInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MaintenanceRecordsRequestBuilderUriTemplate = "{+baseurl}/api/MaintenanceRecords";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MaintenanceRecordsRequestBuilderNavigationMetadata: Record<Exclude<keyof MaintenanceRecordsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: MaintenanceRecordsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MaintenanceRecordsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MaintenanceRecordsRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMaintenanceRecordDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: MaintenanceRecordsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createMaintenanceRecordDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMaintenanceRecordInputDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
