/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDurationTierDtoFromDiscriminatorValue, type DurationTierDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/DurationTiers/Ordered
 */
export interface OrderedRequestBuilder extends BaseRequestBuilder<OrderedRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DurationTierDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DurationTierDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrderedRequestBuilderUriTemplate = "{+baseurl}/api/DurationTiers/Ordered";
/**
 * Metadata for all the requests in the request builder.
 */
export const OrderedRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OrderedRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDurationTierDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
