/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth/Register
 */
export interface RegisterRequestBuilder extends BaseRequestBuilder<RegisterRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     post(requestConfiguration?: RequestConfiguration<RegisterRequestBuilderPostQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<RegisterRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface RegisterRequestBuilderPostQueryParameters {
    email?: string;
    firstName?: string;
    lastName?: string;
    password?: string;
    passwordConfirm?: string;
    username?: string;
}
/**
 * Uri template for the request builder.
 */
export const RegisterRequestBuilderUriTemplate = "{+baseurl}/Auth/Register?Email={Email}&FirstName={FirstName}&LastName={LastName}&Password={Password}&PasswordConfirm={PasswordConfirm}&Username={Username}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RegisterRequestBuilderPostQueryParametersMapper: Record<string, string> = {
    "email": "Email",
    "firstName": "FirstName",
    "lastName": "LastName",
    "password": "Password",
    "passwordConfirm": "PasswordConfirm",
    "username": "Username",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RegisterRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RegisterRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        queryParametersMapper: RegisterRequestBuilderPostQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
