/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAgencyDtoFromDiscriminatorValue, serializeAgencyDto, serializeAgencyInputDto, type AgencyDto, type AgencyInputDto } from '../../models/index.js';
// @ts-ignore
import { AgencyItemRequestBuilderRequestsMetadata, type AgencyItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Agency
 */
export interface AgencyRequestBuilder extends BaseRequestBuilder<AgencyRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.Agency.item collection
     * @param id Unique identifier of the item
     * @returns {AgencyItemRequestBuilder}
     */
     byId(id: number) : AgencyItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AgencyDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AgencyDto[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AgencyDto>}
     */
     post(body: AgencyInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AgencyDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AgencyInputDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AgencyRequestBuilderUriTemplate = "{+baseurl}/api/Agency";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AgencyRequestBuilderNavigationMetadata: Record<Exclude<keyof AgencyRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: AgencyItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AgencyRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AgencyRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createAgencyDtoFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AgencyRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createAgencyDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAgencyInputDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
