/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithInspectionItemRequestBuilder, WithInspectionItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleIncidents/ByPartLocation
 */
export interface ByPartLocationRequestBuilder extends BaseRequestBuilder<ByPartLocationRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehicleIncidents.ByPartLocation.item collection
     * @param inspectionId Unique identifier of the item
     * @returns {WithInspectionItemRequestBuilder}
     */
     byInspectionId(inspectionId: number) : WithInspectionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByPartLocationRequestBuilderUriTemplate = "{+baseurl}/api/VehicleIncidents/ByPartLocation";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByPartLocationRequestBuilderNavigationMetadata: Record<Exclude<keyof ByPartLocationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byInspectionId: {
        navigationMetadata: WithInspectionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["inspectionId"],
    },
};
/* tslint:enable */
/* eslint-enable */
