/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVehicleInspectionDtoFromDiscriminatorValue, type VehicleInspectionDto } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleInspections/ByType/{bookingId}/{type}
 */
export interface WithTypeItemRequestBuilder extends BaseRequestBuilder<WithTypeItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VehicleInspectionDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VehicleInspectionDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithTypeItemRequestBuilderUriTemplate = "{+baseurl}/api/VehicleInspections/ByType/{bookingId}/{type}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithTypeItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithTypeItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createVehicleInspectionDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
