/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithBookingItemRequestBuilder, WithBookingItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleInspections/ByBooking
 */
export interface ByBookingRequestBuilder extends BaseRequestBuilder<ByBookingRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.VehicleInspections.ByBooking.item collection
     * @param bookingId Unique identifier of the item
     * @returns {WithBookingItemRequestBuilder}
     */
     byBookingId(bookingId: number) : WithBookingItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByBookingRequestBuilderUriTemplate = "{+baseurl}/api/VehicleInspections/ByBooking";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByBookingRequestBuilderNavigationMetadata: Record<Exclude<keyof ByBookingRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byBookingId: {
        requestsMetadata: WithBookingItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["bookingId"],
    },
};
/* tslint:enable */
/* eslint-enable */
