/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createVehicleIncidentDtoFromDiscriminatorValue, type VehicleIncidentDto } from '../../../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/VehicleIncidents/ByPartLocation/{inspectionId}/{partLocation}
 */
export interface WithPartLocationItemRequestBuilder extends BaseRequestBuilder<WithPartLocationItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<VehicleIncidentDto[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<VehicleIncidentDto[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPartLocationItemRequestBuilderUriTemplate = "{+baseurl}/api/VehicleIncidents/ByPartLocation/{inspectionId}/{partLocation}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPartLocationItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithPartLocationItemRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createVehicleIncidentDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
