/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithCustomerItemRequestBuilder, WithCustomerItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Bookings/ByCustomer
 */
export interface ByCustomerRequestBuilder extends BaseRequestBuilder<ByCustomerRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.Bookings.ByCustomer.item collection
     * @param customerId Unique identifier of the item
     * @returns {WithCustomerItemRequestBuilder}
     */
     byCustomerId(customerId: number) : WithCustomerItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByCustomerRequestBuilderUriTemplate = "{+baseurl}/api/Bookings/ByCustomer";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByCustomerRequestBuilderNavigationMetadata: Record<Exclude<keyof ByCustomerRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byCustomerId: {
        requestsMetadata: WithCustomerItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["customerId"],
    },
};
/* tslint:enable */
/* eslint-enable */
